stages:
- name: 构建
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: |-
        echo "设置环境变量"
        export GO111MODULE="on"
        export GOPROXY="https://mirrors.aliyun.com/goproxy/"

        echo "开始编译"
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build .
        ls
timeout: 60
notification: {}
